name: Build and Deploy to Azure Container Instances

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/demo-azure:latest .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/demo-azure:latest

    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: myResourceGroup
        dns-name-label: demo-azure-aci-${{ github.run_number }}
        image: ${{ secrets.ACR_NAME }}.azurecr.io/demo-azure:latest
        name: demo-azure-container
        location: eastus
        ports: 80
        registry-login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        registry-username: ${{ secrets.ACR_USERNAME }}
        registry-password: ${{ secrets.ACR_PASSWORD }}